package com.mumu.alarm.bean.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.mumu.alarm.bean.Alarm;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ALARM".
*/
public class AlarmDao extends AbstractDao<Alarm, Long> {

    public static final String TABLENAME = "ALARM";

    /**
     * Properties of entity Alarm.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property AlarmHour = new Property(2, Integer.class, "alarmHour", false, "ALARM_HOUR");
        public final static Property AlarmMinute = new Property(3, Integer.class, "alarmMinute", false, "ALARM_MINUTE");
        public final static Property RingPath = new Property(4, String.class, "ringPath", false, "RING_PATH");
        public final static Property RingName = new Property(5, String.class, "ringName", false, "RING_NAME");
        public final static Property RingType = new Property(6, Integer.class, "ringType", false, "RING_TYPE");
        public final static Property RemindMode = new Property(7, Integer.class, "remindMode", false, "REMIND_MODE");
        public final static Property Sleepy = new Property(8, Integer.class, "sleepy", false, "SLEEPY");
        public final static Property CloseAlarmMode = new Property(9, Integer.class, "closeAlarmMode", false, "CLOSE_ALARM_MODE");
        public final static Property AlarmCircle = new Property(10, byte[].class, "alarmCircle", false, "ALARM_CIRCLE");
    };


    public AlarmDao(DaoConfig config) {
        super(config);
    }
    
    public AlarmDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ALARM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"ALARM_HOUR\" INTEGER," + // 2: alarmHour
                "\"ALARM_MINUTE\" INTEGER," + // 3: alarmMinute
                "\"RING_PATH\" TEXT," + // 4: ringPath
                "\"RING_NAME\" TEXT," + // 5: ringName
                "\"RING_TYPE\" INTEGER," + // 6: ringType
                "\"REMIND_MODE\" INTEGER," + // 7: remindMode
                "\"SLEEPY\" INTEGER," + // 8: sleepy
                "\"CLOSE_ALARM_MODE\" INTEGER," + // 9: closeAlarmMode
                "\"ALARM_CIRCLE\" BLOB);"); // 10: alarmCircle
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ALARM\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Alarm entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        Integer alarmHour = entity.getAlarmHour();
        if (alarmHour != null) {
            stmt.bindLong(3, alarmHour);
        }
 
        Integer alarmMinute = entity.getAlarmMinute();
        if (alarmMinute != null) {
            stmt.bindLong(4, alarmMinute);
        }
 
        String ringPath = entity.getRingPath();
        if (ringPath != null) {
            stmt.bindString(5, ringPath);
        }
 
        String ringName = entity.getRingName();
        if (ringName != null) {
            stmt.bindString(6, ringName);
        }
 
        Integer ringType = entity.getRingType();
        if (ringType != null) {
            stmt.bindLong(7, ringType);
        }
 
        Integer remindMode = entity.getRemindMode();
        if (remindMode != null) {
            stmt.bindLong(8, remindMode);
        }
 
        Integer sleepy = entity.getSleepy();
        if (sleepy != null) {
            stmt.bindLong(9, sleepy);
        }
 
        Integer closeAlarmMode = entity.getCloseAlarmMode();
        if (closeAlarmMode != null) {
            stmt.bindLong(10, closeAlarmMode);
        }
 
        byte[] alarmCircle = entity.getAlarmCircle();
        if (alarmCircle != null) {
            stmt.bindBlob(11, alarmCircle);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Alarm readEntity(Cursor cursor, int offset) {
        Alarm entity = new Alarm( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // alarmHour
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // alarmMinute
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // ringPath
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // ringName
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // ringType
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // remindMode
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // sleepy
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // closeAlarmMode
            cursor.isNull(offset + 10) ? null : cursor.getBlob(offset + 10) // alarmCircle
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Alarm entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAlarmHour(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setAlarmMinute(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setRingPath(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setRingName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setRingType(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setRemindMode(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setSleepy(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setCloseAlarmMode(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setAlarmCircle(cursor.isNull(offset + 10) ? null : cursor.getBlob(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Alarm entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Alarm entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
