package com.mumu.alarm.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ALARM".
 */
public class Alarm implements java.io.Serializable {

    private Long id;
    private String name;
    private Integer alarmHour;
    private Integer alarmMinute;
    private String ringPath;
    private String ringName;
    private Integer ringType;
    private Integer remindMode;
    private Integer sleepy;
    private Integer closeAlarmMode;
    private byte[] alarmCircle;

    public Alarm() {
    }

    public Alarm(Long id) {
        this.id = id;
    }

    public Alarm(Long id, String name, Integer alarmHour, Integer alarmMinute, String ringPath, String ringName, Integer ringType, Integer remindMode, Integer sleepy, Integer closeAlarmMode, byte[] alarmCircle) {
        this.id = id;
        this.name = name;
        this.alarmHour = alarmHour;
        this.alarmMinute = alarmMinute;
        this.ringPath = ringPath;
        this.ringName = ringName;
        this.ringType = ringType;
        this.remindMode = remindMode;
        this.sleepy = sleepy;
        this.closeAlarmMode = closeAlarmMode;
        this.alarmCircle = alarmCircle;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAlarmHour() {
        return alarmHour;
    }

    public void setAlarmHour(Integer alarmHour) {
        this.alarmHour = alarmHour;
    }

    public Integer getAlarmMinute() {
        return alarmMinute;
    }

    public void setAlarmMinute(Integer alarmMinute) {
        this.alarmMinute = alarmMinute;
    }

    public String getRingPath() {
        return ringPath;
    }

    public void setRingPath(String ringPath) {
        this.ringPath = ringPath;
    }

    public String getRingName() {
        return ringName;
    }

    public void setRingName(String ringName) {
        this.ringName = ringName;
    }

    public Integer getRingType() {
        return ringType;
    }

    public void setRingType(Integer ringType) {
        this.ringType = ringType;
    }

    public Integer getRemindMode() {
        return remindMode;
    }

    public void setRemindMode(Integer remindMode) {
        this.remindMode = remindMode;
    }

    public Integer getSleepy() {
        return sleepy;
    }

    public void setSleepy(Integer sleepy) {
        this.sleepy = sleepy;
    }

    public Integer getCloseAlarmMode() {
        return closeAlarmMode;
    }

    public void setCloseAlarmMode(Integer closeAlarmMode) {
        this.closeAlarmMode = closeAlarmMode;
    }

    public byte[] getAlarmCircle() {
        return alarmCircle;
    }

    public void setAlarmCircle(byte[] alarmCircle) {
        this.alarmCircle = alarmCircle;
    }

}
